blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/RE-SS3D/SS3D/discussions/categories/general
    about: General game discussions.
  - name: Ideas
    url: https://github.com/RE-SS3D/SS3D/discussions/categories/ideas
    about: Got an idea about a game feature? Post it to see what others think.
  - name: Questions
    url: https://github.com/RE-SS3D/SS3D/discussions/categories/q-a
    about: Have a question about a task or current system? Feel free to ask.