blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/RE-SS3D/SS3D/discussions/categories/general
    about: Join the discussions here on github with topics such as game design, announcements, ideas/inspiration, Q&A, and more.
