using NUnit.Framework;
using SS3D.Systems.Inventory.Containers;
using SS3D.Systems.Tile;
using System.Collections;
using System.Collections.Generic;
using System.Electricity;
using UnityEngine;

namespace EditorTests
{
    public class CircuitTests
    {
        /// <summary>
        /// Check if batteries charge at equal rate, given they're not full. If they're close to be full, 
        /// check that they're provided with the amount needed to fill them fully, instead of the equal rate.
        /// </summary>
        [Test]
        public void BatteriesChargeAtEqualRatesOrGetFull()
        {

        }

        /// <summary>
        /// Check that batteries that are off don't send power to consumers.
        /// </summary>
        [Test]
        public void BatteriesOffDontProvidePower()
        {

        }

        /// <summary>
        /// Check that a battery with a smaller max power rate than a consumer need cannot make the consumer powered.
        /// </summary>
        [Test]
        public void BatteryCannotSenddPowerGoAboveItsMaxRate()
        {

        }

        /// <summary>
        /// Check that power generated by a bunch of generators, goes first to consumers, and only what's left goes to batteries.
        /// Test if the right amount 
        /// </summary>
        [Test]
        public void PowerGeneratedGoesFirstToConsumers()
        {

        }

        /// <summary>
        /// Check that consumers get inactive when there's not enough power generated.
        /// </summary>
        [Test]
        public void TurnOffConsumersWhenNotEnoughPowerIsGenerated()
        {

        }

        /// <summary>
        /// Check that batteries amount of watt stays between the max allowed amount and level zero.
        /// </summary>
        [Test]
        public void BatteryLevelStayBetweenMaxAmountAndZero()
        {

        }

        /// <summary>
        /// Check that adding more power than possible to a battery returns the correct amount of power added.
        /// Also check that it adds everything when possible.
        /// </summary>
        [Test]
        public void AddingPowerToBatteryReturnsTheCorrectAmountOfPowerAdded()
        {

        }

        /// <summary>
        /// Check that removing more power than possible to a battery returns the correct amount of power removed.
        /// Also check that it removes everything when possible.
        /// </summary>
        [Test]
        public void RemovingPowerFromBatteryReturnsTheCorrectAmountOfPowerRemoved()
        {

        }






        /// <summary>
        /// Check if batteries can send power to consumers even though consumers need more power than batteries can provide.
        /// </summary>
        [Test]
        public void BatteriesSendPowerDespiteNotCoveringAllConsumersNeed()
        {
            // ARRANGE
            BasicBattery batteryOne = CreateBasicBattery(5f, 50f, 50f);
            BasicBattery batteryTwo = CreateBasicBattery(5f, 50f, 50f);
            batteryOne.IsOn = true;
            batteryTwo.IsOn = true;
            BasicPowerConsumer consumerOne = CreateBasicConsumer(2f);
            BasicPowerConsumer consumerTwo = CreateBasicConsumer(7f);

            
            List<IElectricDevice> electricDevices = new List<IElectricDevice>() { batteryOne, batteryTwo, consumerOne, consumerTwo};
            Circuit circuit = CreateCircuit(electricDevices);

            // ACT
            circuit.UpdateCircuitPower();

            // ASSERT
            Assert.IsFalse(batteryOne.StoredPower < 50f);
            Assert.IsTrue(batteryTwo.StoredPower < 50f);
        }

        private static Circuit CreateCircuit(List<IElectricDevice> electricDevices)
        {
            Circuit circuit = new Circuit();
            electricDevices.ForEach(x => circuit.AddElectricDevice(x));
            return circuit;
        }

        private static BasicBattery CreateBasicBattery(float maxPowerRate, float maxCapacity, float storedPower)
        {
            GameObject batteryGo = new GameObject();
            batteryGo.AddComponent<BasicBattery>();
            batteryGo.AddComponent<PlacedTileObject>();
            BasicBattery battery = batteryGo.GetComponent<BasicBattery>();
            battery.Init(maxPowerRate, maxCapacity, storedPower);
            return batteryGo.GetComponent<BasicBattery>();
        }

        private static BasicPowerConsumer CreateBasicConsumer(float powerConsumption)
        {
            GameObject batteryGo = new GameObject();
            batteryGo.AddComponent<BasicPowerConsumer>();
            batteryGo.AddComponent<PlacedTileObject>();
            BasicPowerConsumer consumer = batteryGo.GetComponent<BasicPowerConsumer>();
            consumer.Init(powerConsumption);
            return consumer;
        }
    }
}