#!/usr/bin/env python3
"""Generate an index of external game-icons available for UI work."""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ICONS_ROOT = REPO_ROOT / "Assets" / "Art" / "Icons" / "external icons"
OUTPUT_JSON = REPO_ROOT / "Documents" / "icon-index.json"
OUTPUT_MD = REPO_ROOT / "Documents" / "icon-index.md"
LICENSE_FILE = ICONS_ROOT / "license.txt"

ICON_EXTENSIONS = {"svg", "png"}


@dataclass
class IconRecord:
    name: str
    stem: str
    extension: str
    pack: str
    path: str
    tags: list[str]

    def to_dict(self) -> dict:
        return asdict(self)


def slug_tags(stem: str) -> list[str]:
    return [part for part in stem.lower().split("-") if part]


def walk_external_icons() -> list[IconRecord]:
    records: list[IconRecord] = []

    if not ICONS_ROOT.is_dir():
        return records

    for file_path in sorted(ICONS_ROOT.rglob("*")):
        if not file_path.is_file() or file_path.name.endswith(".meta"):
            continue
        if file_path.suffix.lstrip(".").lower() not in ICON_EXTENSIONS:
            continue

        pack = file_path.parent.name
        relative = file_path.relative_to(REPO_ROOT / "Assets" / "Art" / "Icons")
        stem = file_path.stem

        records.append(
            IconRecord(
                name=file_path.name,
                stem=stem,
                extension=file_path.suffix.lstrip(".").lower(),
                pack=pack,
                path=f"Assets/Art/Icons/{relative.as_posix()}",
                tags=slug_tags(stem),
            )
        )

    return records


def build_pack_stats(records: list[IconRecord]) -> list[dict]:
    counts = Counter(record.pack for record in records)
    return [
        {"pack": pack, "count": count}
        for pack, count in sorted(counts.items(), key=lambda item: (-item[1], item[0]))
    ]


def render_markdown(payload: dict) -> str:
    summary = payload["summary"]
    packs = payload["packs"][:15]

    lines = [
        "# External icon index (agent reference)",
        "",
        "> Generated by `Tools/generate_icon_index.py`. Re-run after adding icons.",
        "",
        "Catalog of [game-icons.net](https://game-icons.net) SVG icons in",
        "`Assets/Art/Icons/external icons/`. Use these freely when building UI —",
        "panels, HUD, machine interfaces, inventory, chat, and interaction menus.",
        "",
        f"**Generated:** {payload['generated_at']}",
        "",
        "## When to use",
        "",
        "Consult this index **before** sourcing or creating new icons when:",
        "",
        "- A UI screen needs a button, status, or category glyph",
        "- You want an icon for a tool, machine, body part, or game concept",
        "- You need to check whether a suitable icon already exists in the project",
        "",
        "These are SVG source files. Import into Unity and assign as sprites or",
        "VectorImage (UI Toolkit) as needed for your UI pipeline.",
        "",
        "## Agent workflow",
        "",
        "1. Search [`icon-index.json`](icon-index.json) by `stem`, `tags`, or `pack`.",
        "2. Use the `path` field as the Unity asset path.",
        "3. Prefer descriptive tag matches (e.g. `welder`, `power`, `medical`).",
        "4. Regenerate after adding icons: `python3 Tools/generate_icon_index.py`.",
        "",
        "### Search examples",
        "",
        "```bash",
        "# Find icons related to power/electricity",
        'jq \'.icons[] | select(.tags[]? | test(\"power|bolt|electric\"))\' Documents/icon-index.json',
        "",
        "# Find a specific icon by filename stem",
        'jq \'.icons[] | select(.stem == \"microscope\")\' Documents/icon-index.json',
        "",
        "# List icons in a contributor pack",
        'jq \'.icons[] | select(.pack == \"delapouite\")\' Documents/icon-index.json',
        "",
        "# Quick grep by keyword",
        'grep -i "wrench" Documents/icon-index.json',
        "```",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|--------|------:|",
        f"| Total icons | {summary['total_icons']} |",
        f"| Contributor packs | {summary['pack_count']} |",
        f"| SVG icons | {summary['svg_count']} |",
        "",
        "## Top contributor packs",
        "",
        "| Pack | Icons |",
        "|------|------:|",
    ]

    for pack in packs:
        lines.append(f"| {pack['pack']} | {pack['count']} |")

    if len(payload["packs"]) > 15:
        lines.append(f"| … | {len(payload['packs']) - 15} more packs in JSON |")

    lines.extend(
        [
            "",
            "## Location",
            "",
            "```",
            "Assets/Art/Icons/external icons/<pack>/<icon-name>.svg",
            "```",
            "",
            "Icons are grouped by original game-icons.net contributor (e.g. `delapouite`,",
            "`lorc`, `caro-asercion`). Filename stems use kebab-case and map to searchable tags.",
            "",
            "Full data: [`icon-index.json`](icon-index.json)",
            "",
            "## License",
            "",
            "Icons are from [game-icons.net](https://game-icons.net) under CC BY 3.0 (some CC0).",
            "See `Assets/Art/Icons/external icons/license.txt` for contributor attribution.",
            "Include \"Icons made by {author}\" in derivative work per the license.",
            "",
            "## Regenerating",
            "",
            "```bash",
            "python3 Tools/generate_icon_index.py",
            "```",
            "",
            "## Related",
            "",
            "- [art-asset-index.md](art-asset-index.md) — models, textures, sounds",
            "- [AGENTS.md](../../AGENTS.md) — agent navigation",
            "",
        ]
    )

    return "\n".join(lines)


def build_payload(records: list[IconRecord]) -> dict:
    packs = build_pack_stats(records)
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "purpose": (
            "Agent reference for locating external game-icons SVGs available for UI work."
        ),
        "source": {
            "root": "Assets/Art/Icons/external icons",
            "origin": "https://game-icons.net",
            "license": "Assets/Art/Icons/external icons/license.txt",
        },
        "summary": {
            "total_icons": len(records),
            "pack_count": len(packs),
            "svg_count": sum(1 for item in records if item.extension == "svg"),
        },
        "packs": packs,
        "icons": [record.to_dict() for record in records],
    }


def main() -> None:
    records = walk_external_icons()
    payload = build_payload(records)

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_JSON.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")

    with OUTPUT_MD.open("w", encoding="utf-8") as handle:
        handle.write(render_markdown(payload))

    summary = payload["summary"]
    print(f"Wrote {OUTPUT_JSON} ({summary['total_icons']} icons, {summary['pack_count']} packs)")
    print(f"Wrote {OUTPUT_MD}")


if __name__ == "__main__":
    main()
