using SS3D.Data.AssetDatabases
;
namespace SS3D.Data.Enums
{
    // This class is autogenerated. Do not modify manually.
    public static class AssetDatabases
    {
        public static DatabaseAsset BodyParts = new DatabaseAsset("BodyParts", "AssetDatabases");
        public static DatabaseAsset InteractionIcons = new DatabaseAsset("InteractionIcons", "AssetDatabases");
        public static DatabaseAsset Items = new DatabaseAsset("Items", "AssetDatabases");
        public static DatabaseAsset Scenes = new DatabaseAsset("Scenes", "AssetDatabases");
        public static DatabaseAsset Settings = new DatabaseAsset("Settings", "AssetDatabases");
    }
}

