using SS3D.Data.AssetDatabases
;
namespace SS3D.Data.Enums
{
    // This class is autogenerated. Do not modify manually.
    public static class BodyPartsIds
    {
        public static DatabaseAsset HumanHandLeft = new DatabaseAsset("HumanHandLeft", "BodyPartsIds");
        public static DatabaseAsset HumanHandRight = new DatabaseAsset("HumanHandRight", "BodyPartsIds");
    }
}

