using SS3D.Data.AssetDatabases
;
namespace SS3D.Data.Enums
{
    // This class is autogenerated. Do not modify manually.
    public static class Scenes
    {
        public static DatabaseAsset Boot = new DatabaseAsset("Boot", "Scenes");
        public static DatabaseAsset Game = new DatabaseAsset("Game", "Scenes");
        public static DatabaseAsset Launcher = new DatabaseAsset("Launcher", "Scenes");
        public static DatabaseAsset Intro = new DatabaseAsset("Intro", "Scenes");
    }
}

