using SS3D.Data.AssetDatabases
;
namespace SS3D.Data.Enums
{
    // This class is autogenerated. Do not modify manually.
    public static class SettingsId
    {
        public static DatabaseAsset ApplicationSettings = new DatabaseAsset("ApplicationSettings", "SettingsId");
        public static DatabaseAsset LogSettings = new DatabaseAsset("LogSettings", "SettingsId");
    }
}

