using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace SS3D.CodeGeneration
{
    public class DatabaseAssetWriter
    {
        /// <summary>
        /// Writes a static class of a DatabaseAssets from an AssetDatabase.  
        /// </summary>
        /// <param name="filePath">Where to write this file to.</param>
        /// <param name="classType">The type of the field elements to use, mainly because assembly conflicts.</param>
        /// <param name="className">The name of the class, currently being the asset database name</param>
        /// <param name="items">the elements to add to this class</param>
        /// <param name="namespaceName">the namespace name to use</param>
        public static void Write(string filePath, Type classType, string className, IEnumerable<string> items, string namespaceName = "SS3D.Data.Enums")
        {
            IEnumerable<string> filtered = items.GroupBy(name => name).Select(nameGroup => nameGroup.Key);

            SourceFile sourceFile = new();

            sourceFile.AppendLine($"using {classType.Namespace}\n;");

            using (new NamespaceScope(sourceFile, namespaceName))
            {
                sourceFile.AppendLine($"// This class is autogenerated. Do not modify manually.");
                sourceFile.AppendLine($"public static class {className}");

                using (new BracesScope(sourceFile))
                {
                    for (int index = 0; index < filtered.ToList().Count; index++)
                    {
                        string member = filtered.ToList()[index];

                        if (string.IsNullOrWhiteSpace(member))
                        {
                            continue;
                        }

                        char[] corrected = member.ToCharArray();
                        corrected[0] = corrected[0].ToString().ToUpper()[0];

                        StringBuilder stringBuilder = new();
                        stringBuilder.Append(corrected);

                        sourceFile.AppendLine($"public static {classType.Name} {stringBuilder} = new {classType.Name}(\"{stringBuilder}\", \"{className}\");"); }
                }
            }

            File.WriteAllText(filePath + "/" + className + ".cs", sourceFile.ToString());
        }
    }
}