#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using Object = UnityEngine.Object;

namespace SS3D.CodeGeneration
{
    public static class DatabaseScriptWriter
    {
        /// <summary>
        /// Writes a static class of a DatabaseAssets from an AssetDatabase.  
        /// </summary>
        /// <param name="filePath">Where to write this file to.</param>
        /// <param name="className">The name of the class, currently being the asset database name</param>
        /// <param name="items">the elements to add to this class</param>
        /// <param name="namespaceName">the namespace name to use</param>
        public static void Write(string filePath, string className, List<Object> items, string namespaceName = "SS3D.Data.Enums")
        {
            items.Sort((obj1, obj2) => string.Compare(obj1.name, obj2.name, StringComparison.InvariantCulture));

            SourceFile sourceFile = new();

            using (new NamespaceScope(sourceFile, namespaceName))
            {
                sourceFile.AppendLine($"// This class is autogenerated. Do not modify manually.");
                sourceFile.AppendLine($"public static class {className}");

                using (new BracesScope(sourceFile))
                {
                    foreach (Object item in items)
                    {
                        string itemPath = AssetDatabase.GetAssetPath(item);

                        if (string.IsNullOrEmpty(itemPath))
                            continue;

                        if (!item || string.IsNullOrWhiteSpace(item.name))
                            continue;

                        char[] corrected = item.name.ToCharArray();
                        corrected[0] = corrected[0].ToString().ToUpper()[0];

                        StringBuilder stringBuilder = new();
                        stringBuilder.Append(corrected);

                        string guid = AssetDatabase.AssetPathToGUID(itemPath);

                        sourceFile.AppendLine($"public const string {stringBuilder} = \"{guid}\";");
                    }
                }
            }

            File.WriteAllText(filePath + "/" + className + ".cs", sourceFile.ToString());
        }
    }
}
#endif