#if UNITY_EDITOR
using JetBrains.Annotations;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;

namespace SS3D.CodeGeneration
{
    public static class DatabaseScriptWriter
    {
        /// <summary>
        /// Writes a static class of a DatabaseAssets from an AssetDatabase.  
        /// </summary>
        /// <param name="filePath">Where to write this file to.</param>
        /// <param name="className">The name of the class, currently being the asset database name</param>
        /// <param name="guids">the elements to add to this class</param>
        /// <param name="namespaceName">the namespace name to use</param>
        public static void Write(string filePath, string className, List<string> guids, string namespaceName = "SS3D.Data.Enums")
        {
            List<(string Guid, string Name)> entries = new(guids.Count);

            entries.AddRange(
                from guid in guids
                let itemPath = AssetDatabase.GUIDToAssetPath(guid)
                where !string.IsNullOrEmpty(itemPath)
                let itemName = Path.GetFileNameWithoutExtension(itemPath)
                where !string.IsNullOrWhiteSpace(itemName)
                select (guid, itemName));

            entries.Sort((left, right) => string.Compare(left.Name, right.Name, StringComparison.InvariantCulture));

            SourceFile sourceFile = new();

            using (new NamespaceScope(sourceFile, namespaceName))
            {
                sourceFile.AppendLine($"// This class is autogenerated. Do not modify manually.");
                sourceFile.AppendLine($"public static class {className}");

                using (new BracesScope(sourceFile))
                {
                    foreach ((string guid, string itemName) in entries)
                    {
                        sourceFile.AppendLine($"public const string {UppercaseFirst(itemName)} = \"{guid}\";");
                    }
                }
            }

            string outputPath = Path.Combine(filePath, $"{className}.cs");
            File.WriteAllText(outputPath, sourceFile.ToString());
        }

        [CanBeNull]
        private static string UppercaseFirst([CanBeNull] string value)
        {
            if (string.IsNullOrEmpty(value))
                return value;

            if (value.Length == 1)
                return char.ToUpperInvariant(value[0]).ToString();

            return char.ToUpperInvariant(value[0]) + value[1..];
        }
    }
}
#endif