name: Automate Roadmap

on:
  issues:
    types:
      - opened
  pull_request:
    branches:
      - develop

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest

   

    steps:
      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: if_issue
        if: github.event.issue
        permissions: read-all|write-all
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: SS3D Roadmap
          column: Backlog
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: if_pr
        if: github.event.pull_request
        permissions: read-all|write-all
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: SS3D Roadmap
          column: In Progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
