name: Automate Roadmap
description: Add issues and pull requests to SS3D roadmap board.
on:
  issues:
    types:
      - opened
  pull_request:
    branches:
      - main
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@RELEASE_VERSION
        with:
          project-url: SS3D Roadmap
          column: Backlog
          github-token: ${{ secrets.GITHUB_TOKEN }}
