name: Add issues and pull requests to SS3D project board.

on:
  issues:
    types:
      - opened
  pull_request:
      - opened

jobs:
  add-to-project:
    name: Add to board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: https://github.com/orgs/RE-SS3D/projects/7
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
