name: Create Project When Milestone Created
on:
  milestone:
    types: [created]
jobs:
  CreateProjectFromMilestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install @actions/core
      - run: npm install @actions/github
      - name: Get list of projects
        uses: octokit/graphql-action@v2.2.24
        id: get-project-title
        with:
          query: |
            query getTitle( $org:String!) {
              organization(login:$org) {
                projectsV2(first:100) {
                  nodes {
                    id
                    title
                    number
                    template
                    closed
                    owner {
                      id
                    }
                  }
                }
              }
            }
          org: RE-SS3D
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_MANAGEMENT_TOKEN }}
      - name: Check for existence of milestone project
        uses: ./.github/actions/check-milestone-exists
        id: check-milestone-exists
        with:
          JSON_LIST_OF_PROJECTS: ${{ steps.get-project-title.outputs.data }}
          PROJECT_NAME: ${{ github.event.milestone.title }}
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_MANAGEMENT_TOKEN }}
      - name: Duplicate Template Project
        uses: octokit/graphql-action@v2.2.24
        id: duplicate-template-project
        if: ${{ steps.check-milestone-exists.outputs.EXISTING_PROJECT_ID == '' }}
        with:
          query: |
            mutation copyTheProject {
              copyProjectV2(input: {ownerId:"MDEyOk9yZ2FuaXphdGlvbjQyNzc4NjQw", projectId:"PVT_kwDOAozAEM4AMVn2", title:"Example"}) {
                clientMutationId  
                projectV2 {
                  id
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_MANAGEMENT_TOKEN }}
      - name: Setup Project
        uses: octokit/graphql-action@v2.2.24
        id: setup-project
        if: ${{ steps.check-milestone-exists.outputs.EXISTING_PROJECT_ID == ''}}
        with:
          query: |
            mutation setupTheProject {
              updateProjectV2(input: {projectId:"${{ fromJSON(steps.duplicate-template-project.outputs.data).copyProjectV2.projectV2.id }}", title:"${{ github.event.milestone.title }}", public:true}) {
                clientMutationId
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_MANAGEMENT_TOKEN }}
      - name: Get repo ID
        uses: octokit/graphql-action@v2.2.24
        id: get-repo-id
        with:
          query: |
            query getRepo( $org:String!) {
              repository(name:"SS3D", owner:$org) {
                id
              }
            }
          org: RE-SS3D
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_MANAGEMENT_TOKEN }}
      - name: Link SS3D Repository to new Project
        uses: octokit/graphql-action@v2.2.24
        id: link-project
        if: ${{ steps.check-milestone-exists.outputs.EXISTING_PROJECT_ID == ''}}
        with:
          query: |
            mutation LinkTheProject {
              linkProjectV2ToRepository(input: {projectId:"${{ fromJSON(steps.duplicate-template-project.outputs.data).copyProjectV2.projectV2.id }}", repositoryId:"${{ fromJSON(steps.get-repo-id.outputs.data).repository.id }}" }) {
                clientMutationId
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_MANAGEMENT_TOKEN }}