#https://game.ci/docs/github/test-runner
name: Run Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode
      - name: Notify discord if tests fail
        uses: rjstone/discord-webhook-notify@v1
        if: failure() && github.event_name != 'pull_request'
        with:
          severity: error
          details: Test runner failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_TEST_RESULTS }}
      - name: Notify discord if tests succeed
        uses: rjstone/discord-webhook-notify@v1
        if: success() && github.event_name != 'pull_request'
        with:
          severity: info
          details: Test runner passed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_TEST_RESULTS }}
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts
