name: Public Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.12f1
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Decrypt the license file
        run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_KEY }} >> .github/Unity_v2019.x.ulf

      - name: Activate Unity
        run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0

      - name: Build Windows Player
        run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -accept-apiupdate -logFile -projectPath . -buildTarget StandaloneWindows64 -customBuildTarget StandaloneWindows64 -customBuildPath ./dist/win64/ -customBuildName RESS3D.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: RESS3D_WIN
          path: ./dist/win64

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: RESS3D_WIN
      - name: Get version tag
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Archive build
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./RESS3D_${{ steps.tag_name.outputs.SOURCE_TAG }}.zip ./RESS3D_WIN
      - name: Attach build to release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: ./RESS3D_${{ steps.tag_name.outputs.SOURCE_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
