#https://game.ci/docs/github/test-runner
name: Run Tests
on: [push, workflow_dispatch]
jobs:
  run_tests:
    name: Run Playmode Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Make build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildName: SS3D
          targetPlatform: StandaloneWindows
          buildsPath: Builds
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: PlayMode
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts